{
 "title": "Alerts dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mainnet",
    "query": "\"OpsMain\",\"Uphold\",\"IdRamp-Main\",\"GlobaliD-Main\",\"Snowbridge\",\"FinClusive\",\"xertify\",\"LiquidAvatar\""
   }
  ]
 },
 "panels": [
  {
   "title": "MainNet Unreachable Nodes",
   "type": "graph",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Unreachable Node(s)" } },
   "yaxes": [
    { "format": "Unreachable Node(s)" }
   ],
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"OpsMain\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"IdRamp-Main\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"GlobaliD-Main\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"Snowbridge\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"FinClusive\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"xertify\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"LiquidAvatar\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"anonyome\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"ici_selfdid_main\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"bizsecure-indicionet-node1\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"networks_synergy_main\"}"
    }
   ]
  },
  {
   "title": "TestNet Unreachable Nodes",
   "type": "graph",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Unreachable Node(s)" } },
   "yaxes": [
    { "format": "Unreachable Node(s)" }
   ],
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"OpsNode\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"lownode\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"lownode2\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"cynjanode\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"ent-vl\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"Blockster\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"IdRamp\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"GlobaliD\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"lorica-identity-node1\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"Procivis\"}"
    }
   ]
  },
  {
   "title": "DemoNet Unreachable Nodes",
   "type": "graph",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Unreachable Node(s)" } },
   "yaxes": [
    { "format": "Unreachable Node(s)" }
   ],
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"opsnode-dn\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"IdRamp-Demo1\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"IdRamp-Demo2\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"IdRamp-Demo3\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"cysecure\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"absolutely_zero\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"GlobaliD-Demo\"}"
    }
   ]
  },
  {
   "title": "URGENT: MainNet Unreachable Nodes",
   "type": "graph",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Unreachable Node(s)" } },
   "yaxes": [
    { "format": "Unreachable Node(s)" }
   ],
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"OpsMain\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"anonyome\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"IdRamp-Main\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"FinClusive\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"Snowbridge\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"GlobaliD-Main\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"xertify\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"LiquidAvatar\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"ici_selfdid_main\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"bizsecure-indicionet-node1\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9106\",job=\"node-external\",node_name=\"networks_synergy_main\"}"
    }
   ]
  },
  {
   "title": "URGENT: TestNet Unreachable Nodes",
   "type": "graph",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Unreachable Node(s)" } },
   "yaxes": [
    { "format": "Unreachable Node(s)" }
   ],
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"OpsNode\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"lownode\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"lownode2\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"cynjanode\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"ent-vl\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"Blockster\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"IdRamp\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"GlobaliD\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"lorica-identity-node1\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9100\",job=\"node-external\",node_name=\"Procivis\"}"
    }
   ]
  },
  {
   "title": "URGENT: DemoNet Unreachable Nodes",
   "type": "graph",
   "description": "Indy Validator Unreachable Nodes (0 is best)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Unreachable Node(s)" } },
   "yaxes": [
    { "format": "Unreachable Node(s)" }
   ],
   "targets": [
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"opsnode-dn\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"IdRamp-Demo1\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"IdRamp-Demo2\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"IdRamp-Demo3\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"cysecure\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"absolutely_zero\"}"
    },
    {
     "expr": "indy_unreachable_nodes_count{instance=\"localhost:9105\",job=\"node-external\",node_name=\"GlobaliD-Demo\"}"
    }
   ]
  },
  {
   "title": "Main Net Consensus Status",
   "type": "graph",
   "description": "Indy Validator Not In Consensus status (0 is best)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Out of Consensus" } },
   "yaxes": [
    { "format": "Out of Consensus" }
   ],
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9106\",job=\"node-external\",node_name=\"FinClusive\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9106\",job=\"node-external\",node_name=\"GlobaliD-Main\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9106\",job=\"node-external\",node_name=\"IdRamp-Main\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9106\",job=\"node-external\",node_name=\"LiquidAvatar\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9106\",job=\"node-external\",node_name=\"OpsMain\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9106\",job=\"node-external\",node_name=\"Snowbridge\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9106\",job=\"node-external\",node_name=\"ici_selfdid_main\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9106\",job=\"node-external\",node_name=\"anonyome\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9106\",job=\"node-external\",node_name=\"bizsecure-indicionet-node1\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9106\",job=\"node-external\",node_name=\"networks_synergy_main\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9106\",job=\"node-external\",node_name=\"xertify\"}"
    }
   ]
  },
  {
   "title": "TestNet Consensus Status",
   "type": "graph",
   "description": "TestNet Not In Consensus status (0 is best)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Out of Consensus" } },
   "yaxes": [
    { "format": "Out of Consensus" }
   ],
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=\"Blockster\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=\"OpsNode\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=\"GlobaliD\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=\"IdRamp\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=\"Procivis\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=\"cynjanode\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=\"cysecure-itn\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=\"ent-vl\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=\"idlab-node01\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=\"lorica-identity-node1\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=\"lownode\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=\"lownode2\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9100\",job=\"node-external\",node_name=\"monokee-node0\"}"
    }
   ]
  },
  {
   "title": "DemoNet Consensus Status",
   "type": "graph",
   "description": "Indy Validator Not In Consensus status (0 is best)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Out of Consensus" } },
   "yaxes": [
    { "format": "Out of Consensus" }
   ],
   "targets": [
    {
     "expr": "indy_consensus{instance=\"localhost:9105\",job=\"node-external\",node_name=\"GlobaliD-Demo\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9105\",job=\"node-external\",node_name=\"IdRamp-Demo3\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9105\",job=\"node-external\",node_name=\"absolutely_zero\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9105\",job=\"node-external\",node_name=\"cysecure\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9105\",job=\"node-external\",node_name=\"opsnode-dn\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9105\",job=\"node-external\",node_name=\"IdRamp-Demo1\"}"
    },
    {
     "expr": "indy_consensus{instance=\"localhost:9105\",job=\"node-external\",node_name=\"IdRamp-Demo2\"}"
    }
   ]
  }
 ]
}