{
 "title": "Performance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network_port",
    "query": "\"localhost:9106\",\"localhost:9105\",\"localhost:9100\""
   },
   {
    "name": "network_name",
    "query": "Indicio MainNet,Indicio DemoNet,Indicio TestNet"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Name",
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "repeat": "network_name",
   "fieldConfig": { "defaults": { "unit": "$network_name" } },
   "options": {
    "content": "\n<div class=\"text-center\">\n  <h1>$network_name</p>\n</div>\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "repeat": "network_port",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(indy_total_nodes_count{job=\"node-external\",instance=${network_port}})"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 0 },
   "repeat": "network_port",
   "fieldConfig": { "defaults": { "unit": "Txns" } },
   "yaxes": [
    { "format": "Txns" }
   ],
   "targets": [
    {
     "expr": "max(indy_transaction_count{ident=\"ledger\", job=\"node-external\", instance=${network_port}})"
    }
   ]
  },
  {
   "title": "Avg Writes/Second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "repeat": "network_port",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(indy_average_per_second{job=\"node-external\",ident=\"write_transactions\",instance=${network_port}})"
    },
    {
     "expr": "indy_average_per_second{job=\"node-external\",ident=\"write_transactions\",instance=${network_port}}"
    }
   ]
  },
  {
   "title": "Avg Reads/Second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "repeat": "network_port",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(indy_average_per_second{job=\"node-external\",ident=\"read_transactions\",instance=${network_port}})"
    },
    {
     "expr": "indy_average_per_second{job=\"node-external\",ident=\"read_transactions\",instance=${network_port}}"
    }
   ]
  },
  {
   "title": "Network Name",
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "$network_name" } },
   "options": {
    "content": "\n<div class=\"text-center\">\n  <h1>$network_name</p>\n</div>\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(indy_total_nodes_count{job=\"node-external\",instance=${network_port}})"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Txns" } },
   "yaxes": [
    { "format": "Txns" }
   ],
   "targets": [
    {
     "expr": "max(indy_transaction_count{ident=\"ledger\", job=\"node-external\", instance=${network_port}})"
    }
   ]
  },
  {
   "title": "Avg Writes/Second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(indy_average_per_second{job=\"node-external\",ident=\"write_transactions\",instance=${network_port}})"
    },
    {
     "expr": "indy_average_per_second{job=\"node-external\",ident=\"write_transactions\",instance=${network_port}}"
    }
   ]
  },
  {
   "title": "Avg Reads/Second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(indy_average_per_second{job=\"node-external\",ident=\"read_transactions\",instance=${network_port}})"
    },
    {
     "expr": "indy_average_per_second{job=\"node-external\",ident=\"read_transactions\",instance=${network_port}}"
    }
   ]
  },
  {
   "title": "Network Name",
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "$network_name" } },
   "options": {
    "content": "\n<div class=\"text-center\">\n  <h1>$network_name</p>\n</div>\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(indy_total_nodes_count{job=\"node-external\",instance=${network_port}})"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Txns" } },
   "yaxes": [
    { "format": "Txns" }
   ],
   "targets": [
    {
     "expr": "max(indy_transaction_count{ident=\"ledger\", job=\"node-external\", instance=${network_port}})"
    }
   ]
  },
  {
   "title": "Avg Writes/Second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(indy_average_per_second{job=\"node-external\",ident=\"write_transactions\",instance=${network_port}})"
    },
    {
     "expr": "indy_average_per_second{job=\"node-external\",ident=\"write_transactions\",instance=${network_port}}"
    }
   ]
  },
  {
   "title": "Avg Reads/Second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(indy_average_per_second{job=\"node-external\",ident=\"read_transactions\",instance=${network_port}})"
    },
    {
     "expr": "indy_average_per_second{job=\"node-external\",ident=\"read_transactions\",instance=${network_port}}"
    }
   ]
  }
 ]
}